### ISSUE TITLE
[Dúvida] Inscrição e valor

### ISSUE THREAD

**Issue by lucasmahle** [ccuffs/Viagem-Latino#1]
Quando vai abrir as inscrições?
O valor já foi definido?

**Comment by rafinhadufluxo** [comment]
Olá Lucas,

Os organizadores da latino estão com problema à respeito da inscrição. E ainda não abriram a inscrição, iremos avisar-los o máximo dois dias de antecedência (a abertura da inscrição). E o valor da inscrição é R$ 25 reais. E estamos verificando o hostel.

Logo postaremos no instagram e facebook, todas as informações. 

att,

**Comment by lucasmahle** [comment]
Ok Rafa, vou ficar de olho.

Muito obrigado.

**Comment by watsonmaster** [comment]
Conforme o post do Facebook terão 35 vagas, já foi definido algum critério de seleção ou sera por ordem de inscrição?

**Comment by annnyc** [comment]
Será por ordem de inscrição.
